# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-13 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=100, null=True)),
                ('publisher', models.CharField(max_length=50)),
                ('genre', models.CharField(choices=[('phi', 'philosophy'), ('soc', 'social'), ('nat', 'nature'), ('eng', 'english'), ('lan', 'language')], max_length=3)),
                ('due', models.DateTimeField(verbose_name='Due Date')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('cid', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('c_type', models.CharField(choices=[('prof', 'professor'), ('stud', 'student')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('name', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Seminar_room',
            fields=[
                ('room_name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('available_num', models.IntegerField()),
                ('lname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Library')),
            ],
        ),
        migrations.CreateModel(
            name='Seminar_use',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Client')),
                ('rname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Seminar_room')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('sid', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('s_type', models.CharField(choices=[('lib', 'librarian'), ('room_adm', 'room_administrator'), ('adm', 'administrator')], max_length=8)),
                ('phone_n', models.CharField(max_length=4)),
                ('lname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Library')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='cid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Client'),
        ),
        migrations.AddField(
            model_name='book',
            name='lname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Library'),
        ),
    ]
