# Generated by Django 2.0.5 on 2018-05-22 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeminarRoom',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('available_num', models.IntegerField(db_column='AVAILABLE_NUM')),
            ],
            options={
                'db_table': 'seminar_room',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeminarUse',
            fields=[
                ('cid', models.ForeignKey(db_column='Cid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='home.Client')),
                ('date', models.DateField(db_column='DATE')),
            ],
            options={
                'db_table': 'seminar_use',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='seminar_room',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='seminar_use',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='seminar_use',
            name='rname',
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='library',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='Seminar_room',
        ),
        migrations.DeleteModel(
            name='Seminar_use',
        ),
    ]
