# Generated by Django 2.0.5 on 2018-05-23 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20180522_2144'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
        migrations.AlterModelTable(
            name='client',
            table='client',
        ),
        migrations.AlterModelTable(
            name='library',
            table='library',
        ),
        migrations.AlterModelTable(
            name='staff',
            table='staff',
        ),
    ]
